name: Test Self Action
permissions:
  contents: read
"on":
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - ".github/workflows/ci-self.yml"
      - "dist/*"
  schedule:
    # At 06:00 on Sunday.
    - cron: "0 6 * * 0"

jobs:
  test-self-action:
    name: Make sure the action works on a clean machine without building
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: ./
        with:
          milliseconds: 1000
