---
name: CI
permissions:
  contents: write
"on":
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/ci.yml"
      - ".gitignore"
      - ".gitattributes"
      - ".yamllint"
      - "LICENSE"
      - "src/**"
      - "tests/**"
      - "package.json"
      - "package-lock.json"
  schedule:
    # At 05:00 on Sunday.
    - cron: "0 5 * * 0"

jobs:
  package:
    name: Run Everything and Package Distribution File
    runs-on: ubuntu-latest

    steps:
      - name: check out the codebase
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: set up python 3
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5 # tag=v4
        with:
          python-version: "3.8"

      - name: setup node 16 and activate npm download cache
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: 16
          cache: "npm" # one of "npm", "yarn" or "pnpm"

      - name: setup/activate pre-commit cache
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77 # tag=v3
        with:
          path: ~/.cache/pre-commit
          key: {% raw %}${{ hashFiles('**/.pre-commit-config.yaml') }}{% endraw %}

      # https://stackoverflow.com/a/69944063/13953427
      - name: install npm dependencies (including dev)
        run: npm ci -D

      - name: install dev dependencies
        run: pip3 install -r requirements-dev.txt

      # same order as in 'npm run all':
      - name: Compile Typescript.
        run: npm run build

      - name: Format Code.
        run: npm run format

      - name: Lint Code.
        run: npm run lint

      - name: Compile source into single file.
        run: npm run package

      - name: Test.
        run: npm run test

      - name: Upload coverage to Codecov and create Pull Request comment
        uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378 # tag=v3

      - name: Commit generated dist.
        uses: stefanzweifel/git-auto-commit-action@49620cd3ed21ee620a48530e81dba0d139c9cb80 # tag=v4
        with:
          commit_message: "chore: generate packaged distribution file for {% raw %}${{ github.sha }}{% endraw %} \n {% raw %}${{ github.event.head_commit.message }}{% endraw %}"
          file_pattern: "dist/*"
